# Generated by Django 3.2.8 on 2021-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_remove_events_event_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profile_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
