# Generated by Django 3.2.8 on 2021-11-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20211113_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
