# Generated by Django 3.2.8 on 2021-11-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
