# Generated by Django 3.2.8 on 2021-11-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0014_alter_attendance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
