# Generated by Django 3.2.8 on 2021-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0017_auto_20211205_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
