# Generated by Django 3.2.8 on 2021-12-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0019_auto_20211211_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
