# Generated by Django 3.2.8 on 2021-12-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0020_auto_20211211_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
